# Generated by Django 5.0.3 on 2025-04-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routereport',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason for report closure', null=True),
        ),
        migrations.AddField(
            model_name='routereport',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10),
        ),
    ]
