# Generated by Django 5.0.3 on 2025-04-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citzen',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
